init:
  - git config --global core.autocrlf input

branches:
  only:
    - master

environment:
  NODEJS_VERSION: '0.12.4'
  SIGNTOOL_PATH: 'C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A/Bin/SignTool.exe'

cache:
  - "node_modules -> package.json"
  - "src/node_modules -> src/package.json"
  - "%APPDATA%/npm-cache"

install:
  - ps: Install-Product node $env:NODEJS_VERSION
  - npm install -g gulp
  - npm install

build_script:
  - node --version
  - npm --version
  - gulp pack:win32:installer
  - gulp pack:win32:portable

artifacts:
  - path: dist\*

deploy:
  - provider: GitHub
    auth_token:
      secure: 5HXfg0QXRwPIx6Hjad37cMQvzBXXGnlX31Wnq+S7gFQw5cR9QV8BlgwWlFfuHuu2
    artifact: dist\*
    draft: true
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
